### ISSUE TITLE
Problem with Mgnify Sequence Search

### ISSUE THREAD

**Issue by exsto1** [EBI-Metagenomics/notebooks#25]
Hello!
It appears that your pHMMER Sequence Search service for the Mgnify database isn't working.
Neither manual search via website nor API.
The queue is stuck with above 6000 jobs and it's not going down for about a week now.
Without it, protein search is impossible to perform without downloading full database files...

Apologies if it's not the right place for the issue ticket, but helpdesk requests are being ignored.
Thank you!

**Comment by SandyRogers** [comment]
Thank you for reporting your experience with the sequence search. The MGnify team are aware of and are looking into the issues with that it. Our [helpdesk](https://www.ebi.ac.uk/about/contact/support/metagenomics) is indeed the best place to contact us for support with issues like this, and it is queued but certainly not ignored. I can see a heldesk request similar to this issue was received 3 days ago, and we will reply to that thread as soon as possible. I will close this issue in favour of that helpdesk thread.
