### ISSUE TITLE
error in Cross-study analysis.ipynb: argument is not a matrix

### ISSUE THREAD

**Issue by taylorreiter** [EBI-Metagenomics/notebooks#3]
This code block
```
metadata <- mgnify_get_analyses_metadata(mg, accessions)
head(metadata)
```
produces this error in the binder environment:
```
  |======================================                                |  54%

Error in t.default(unlist(c(json$attributes[baseattrlist], metlist))): argument is not a matrix
Traceback:

1. mgnify_get_analyses_metadata(mg, accessions)
2. plyr::llply(as.list(accessions), function(x) mgnify_get_single_analysis_metadata(client, 
 .     x, usecache = usecache), .progress = "text")
3. loop_apply(n, do.ply)
4. (function (i) 
 . {
 .     piece <- pieces[[i]]
 .     if (.inform) {
 .         res <- try(.fun(piece, ...))
 .         if (inherits(res, "try-error")) {
 .             piece <- paste(utils::capture.output(print(piece)), 
 .                 collapse = "\n")
 .             stop("with piece ", i, ": \n", piece, call. = FALSE)
 .         }
 .     }
 .     else {
 .         res <- .fun(piece, ...)
 .     }
 .     progress$step()
 .     res
 . })(43L)
5. .fun(piece, ...)
6. mgnify_get_single_analysis_metadata(client, x, usecache = usecache)
7. mgnify_attr_list_to_df_row(top_data, metadata_key = "analysis-summary")
8. as.data.frame(t(unlist(c(json$attributes[baseattrlist], metlist))), 
 .     stringsAsFactors = F)
9. t(unlist(c(json$attributes[baseattrlist], metlist)))
10. t.default(unlist(c(json$attributes[baseattrlist], metlist)))
```

**Comment by SandyRogers** [comment]
Hi @taylorreiter, sorry for the vacation-delayed response.
Thanks for reporting this bug.

Could you please help me to track it down?
1. Was this an intermittent bug or did it start working again later / now? (It is possible the MGnify API had a short downtime causing bad data to be returned.)
2. If it is still not working: 
  - What were the MGYA `accessions` you used? Was it those given in the example or did you pull from a different Study? If so, what were the Studies' MGYS accessions?
  - You mention Binder. Are you running these notebooks in your own Binder environment rather than on the EMBL Shiny Proxy server? If so, could you please list the libraries and versions you have installed? (You can run `sessionInfo()` in an R Notebook cell to get this list)

Many thanks

**Comment by taylorreiter** [comment]
I just tested it again, and it's working now, so I'm guessing it was a short API downtime -- thank you for your help in solving this!

**Comment by SandyRogers** [comment]
Great! And sorry about the short API downtime. This does happen now and then (although we're working on improving reliability and performance), but I'll close this issue for now. Feel free to reach us here or via the MGnify website Helpdesk if you run into any other issues.
